# -*- coding: utf-8 -*-
"""24-09-02-hellow-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezxY5p7SFMzGkCQu6i3acljWpeVyvQ66
"""

print("Hellow World")

print("Computer Programming basic class")

#many power mode 는 조심해서 사용하세요
#no ppower mode 에서도 코딩이 가능할까요?
#중간정도의 힘으로 코드를 잘 만들어 봅시다.